require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VoucherAccountsController do

  # This should return the minimal set of attributes required to create a valid
  # VoucherAccount. As you add validations to VoucherAccount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all voucher_accounts as @voucher_accounts" do
      voucher_account = VoucherAccount.create! valid_attributes
      get :index
      assigns(:voucher_accounts).should eq([voucher_account])
    end
  end

  describe "GET show" do
    it "assigns the requested voucher_account as @voucher_account" do
      voucher_account = VoucherAccount.create! valid_attributes
      get :show, :id => voucher_account.id.to_s
      assigns(:voucher_account).should eq(voucher_account)
    end
  end

  describe "GET new" do
    it "assigns a new voucher_account as @voucher_account" do
      get :new
      assigns(:voucher_account).should be_a_new(VoucherAccount)
    end
  end

  describe "GET edit" do
    it "assigns the requested voucher_account as @voucher_account" do
      voucher_account = VoucherAccount.create! valid_attributes
      get :edit, :id => voucher_account.id.to_s
      assigns(:voucher_account).should eq(voucher_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VoucherAccount" do
        expect {
          post :create, :voucher_account => valid_attributes
        }.to change(VoucherAccount, :count).by(1)
      end

      it "assigns a newly created voucher_account as @voucher_account" do
        post :create, :voucher_account => valid_attributes
        assigns(:voucher_account).should be_a(VoucherAccount)
        assigns(:voucher_account).should be_persisted
      end

      it "redirects to the created voucher_account" do
        post :create, :voucher_account => valid_attributes
        response.should redirect_to(VoucherAccount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voucher_account as @voucher_account" do
        # Trigger the behavior that occurs when invalid params are submitted
        VoucherAccount.any_instance.stub(:save).and_return(false)
        post :create, :voucher_account => {}
        assigns(:voucher_account).should be_a_new(VoucherAccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VoucherAccount.any_instance.stub(:save).and_return(false)
        post :create, :voucher_account => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voucher_account" do
        voucher_account = VoucherAccount.create! valid_attributes
        # Assuming there are no other voucher_accounts in the database, this
        # specifies that the VoucherAccount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VoucherAccount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => voucher_account.id, :voucher_account => {'these' => 'params'}
      end

      it "assigns the requested voucher_account as @voucher_account" do
        voucher_account = VoucherAccount.create! valid_attributes
        put :update, :id => voucher_account.id, :voucher_account => valid_attributes
        assigns(:voucher_account).should eq(voucher_account)
      end

      it "redirects to the voucher_account" do
        voucher_account = VoucherAccount.create! valid_attributes
        put :update, :id => voucher_account.id, :voucher_account => valid_attributes
        response.should redirect_to(voucher_account)
      end
    end

    describe "with invalid params" do
      it "assigns the voucher_account as @voucher_account" do
        voucher_account = VoucherAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VoucherAccount.any_instance.stub(:save).and_return(false)
        put :update, :id => voucher_account.id.to_s, :voucher_account => {}
        assigns(:voucher_account).should eq(voucher_account)
      end

      it "re-renders the 'edit' template" do
        voucher_account = VoucherAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VoucherAccount.any_instance.stub(:save).and_return(false)
        put :update, :id => voucher_account.id.to_s, :voucher_account => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voucher_account" do
      voucher_account = VoucherAccount.create! valid_attributes
      expect {
        delete :destroy, :id => voucher_account.id.to_s
      }.to change(VoucherAccount, :count).by(-1)
    end

    it "redirects to the voucher_accounts list" do
      voucher_account = VoucherAccount.create! valid_attributes
      delete :destroy, :id => voucher_account.id.to_s
      response.should redirect_to(voucher_accounts_url)
    end
  end

end
